# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Comment: create, read, update, delete
  User: create, read, update, delete
  Word: create, read, update, delete
  WordSet: create, read, update, delete
  WordSetToWord: create, read, update, delete
